#!/bin/bash
export JAVA_HOME=/usr/lib/jvm/jre
export EC2_HOME=/opt/aws/apitools/ec2
export AWS_RDS_HOME=/opt/aws/apitools/rds
export PATH="$EC2_HOME/bin:$AWS_RDS_HOME/bin:$PATH"

export EC2_KEY_DIR=/home/ec2-user/.ec2
export EC2_PRIVATE_KEY=${EC2_KEY_DIR}/pk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.pem
export EC2_CERT=${EC2_KEY_DIR}/cert-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.pem
